# Generated by Django 5.2.17 on 2026-08-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'natureza',
                'verbose_name_plural': 'naturezas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('origem', models.CharField(choices=[('bdlp', 'Biblioteca Digital (BDLP v9)'), ('lina', 'DESCRICAO RECPSP (coordenacao)')], default='bdlp', max_length=10, verbose_name='origem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'assunto',
                'verbose_name_plural': 'assuntos',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['origem', 'ordem'], name='taxonomia_assunto_origem')],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('nivel', models.CharField(choices=[('macroetapa', 'Macroetapa'), ('subcategoria', 'Subcategoria'), ('microcategoria', 'Microcategoria')], max_length=20, verbose_name='nivel')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='taxonomia.categoriaprocessual', verbose_name='categoria pai')),
            ],
            options={
                'verbose_name': 'categoria processual',
                'verbose_name_plural': 'categorias processuais',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['nivel', 'ordem'], name='taxonomia_cat_nivel_ordem'), models.Index(fields=['pai', 'ordem'], name='taxonomia_cat_pai_ordem')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('nivel', 'macroetapa'), ('pai__isnull', True)), models.Q(models.Q(('nivel', 'macroetapa'), _negated=True), ('pai__isnull', False)), _connector='OR'), name='taxonomia_raiz_so_para_macroetapa'), models.UniqueConstraint(fields=('pai', 'ordem'), name='taxonomia_ordem_unica_entre_irmas', nulls_distinct=False)],
            },
        ),
    ]
